apiVersion: v1
kind: Service
metadata:
  name: vehicle-store-api-service
  namespace: vehicle-store
  labels:
    app: vehicle-store-api
    component: backend
spec:
  selector:
    app: vehicle-store-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: LoadBalancer