apiVersion: v1
kind: Secret
metadata:
  name: vehicle-store-secrets
  namespace: vehicle-store
type: Opaque
data:
  postgres-user: YWRtaW4=
  postgres-password: cGFzc3dvcmQ=
  postgres-db: dmVoaWNsZV9zdG9yZQ==